In [ ]:
# 3. Begin
print ('Hi Again')

Hi Again


In [ ]:
# 2. String Manipulation
s="Hello"
print (s)
print (s[0])
print (s[0],s[1],s[2],s[3],s[4])
print (s[0],s[1],s[2],s[-2],s[-1])
print (s[0],s[1],s[2],s[-2],s[-1],len(s))
n= 'Z C R'
print (n[0],n[1],n[2],n[-2],n[-1],len(n))
print (n+" World" + ", I am Zingya")

Hello
H
H e l l o
H e l l o
H e l l o 5
Z   C   R 5
Z C R World, I am Zingya


In [ ]:
# 3. String is immutable
s='Hello'
print (s)
type (s)
#s[1]='b' #won't work

Hello


str

In [ ]:
# 4. Strings andn Intergers
s='Hello'
num=10
print(num)
#print(s+num) #error
print(s+str(num))

10
Hello10


In [ ]:
# 5. String Methods
s='hello Zingya C Raman'
print (s)
print (str.lower(s))
print (str.upper(s))
print (str.strip(s))
print (str.isalpha(s))
print (str.isdigit(s))
print (str.isalnum(s))
print (str.isspace(s))
#print (s.replace(s,'Old'))
print ('\n')
n='Hii'
print (n)
print (n.lower())
print (n.upper())
print (n.strip())
print (n.isalpha())
print (n.isdigit())
print (n.isalnum())
print (n.isspace())

hello Zingya C Raman
hello zingya c raman
HELLO ZINGYA C RAMAN
hello Zingya C Raman
False
False
False
False


Hii
hii
HII
Hii
True
False
True
False


In [ ]:
# 6.
s="Hello"
print (s[1:3])
print ('\n')
print (s[1:])
print ('\n')
print (s[-4:3])

el


ello


el


In [ ]:
# String Formatting
str1='Hello %s, %d' %('World',10)
print (str1)
str2='Hello {}, {}'.format('world',10)
print (str2)
str3= 'Hello {wd}, {num}'.format(num=10,wd='World')
print (str3)
str4= 'Hello {wd:10}, {num:.3f}'.format(num=10.0, wd='World')
print (str4)

Hello World, 10
Hello world, 10
Hello World, 10
Hello World     , 10.000


In [ ]:
# If statements
num=40
if num<5:
  print ('num is smaller than 5')
if num>5:
  print ('num is greater than 5')
elif num ==5:
  print ('num is 5')
else:
  print ('num is smaller than 5')

num is greater than 5


In [ ]:
# Function cells
print (type(32))
type (32)
print (int(32))
#int ('Hello')
int (-2.3)
import math
print (math.sin(3.1416))
print (math.cos(3.1416))
print (math.tan(3.1416))
print (math.atan(3.1416))
print (math.asin(0.87))
print (math.acos(-1))
print (math.sqrt(2))
print (math.ceil(342.89))
print (math.comb(8,2))
print (math.copysign(34,-3.2))
print (math.degrees(6))
#print (math.dist(8,4))
print (math.factorial(4))
#help ('math')

<class 'int'>
32
-7.346410206643587e-06
-0.9999999999730151
7.346410206841829e-06
1.2626279315447793
1.0552023205488061
3.141592653589793
1.4142135623730951
343
28
-34.0
343.77467707849394
24


In [ ]:
# def function_name (parameters): BLOCK
def print_name():
  print ("I'm Zingya")
  print ("I'm from the dept. of AgFE")
print_name()

I'm Zingya
I'm from the dept. of AgFE


In [ ]:
# Function Parameters and arguments
def print_twice(arg1):
  print(arg1)
  print(arg1)
print_twice(math.pi)
print_twice('Spam'*4)

3.141592653589793
3.141592653589793
SpamSpamSpamSpam
SpamSpamSpamSpam


In [ ]:
# Function Returns
def print_twice(arg1):
  print(arg1)
  print (arg1)
result= print_twice('Bing')
print(result)

Bing
Bing
None


In [ ]:
# Function Returns
def print_twice(arg1):
  print(arg1)
  return arg1*2
result= print_twice('Bing')
print(result)

Bing
BingBing


In [ ]:
# Function Returns
def print_twice(arg1,arg2):
  #print(arg1)
  #return arg1+arg2
  return arg1,arg2
#result= print_twice('Bing','Zingya')
res1,res2= print_twice('Bing','Zingya')
#print(result)
print(res1)
print(res2)

Bing
Zingya


In [ ]:
# Function checking type of arguments: recursive
def factorial(n):
  if not isinstance(n,int):
    print ('Factorial is only defined for Integers')
    return None
  elif n<0:
    print ('Factorial is not defined for negative Integers')
    return None
  elif n==0:
    return 1
  else:
    return n * factorial(n-1)
factorial(4)
#factorial (-234)
#factorial (32.354)

24

In [ ]:
def fact(n):
  if not isinstance(n,int):
    print ('Factorial is only defined for Integers')
    return None
  elif n<0:
    print ('Factorial is not defined for negative Integers')
    return None
  elif n==0:
    return 1
  else:
    return factorial(n)
fact(3)

6

In [ ]:
def func1(arg1, arg2=None):
  if arg2 is None:
    print (arg1)
  else:
    print (arg1,arg2)
func1('hello')
func1('hello','world')

hello
hello world


In [ ]:
# Importing with 'from' function
from math import pi
print (pi)
from math import cos
print (cos(pi))

3.141592653589793
-1.0


In [ ]:
# Global/Local variables
global_var=1
def func1():
  global_var=2
  return global_var
func1()
global_var

1

In [ ]:
global_var=1
def func2():
  global global_var
  global_var=3
  return global_var
func2()
global_var

3

In [ ]:
# Eg
import math
a=2;
b=5;
c=(a**2+b**2)**(0.5);
d=math.sqrt(c);
f=c*d;
g=c/d;
h= a*math.sin(b);
i= factorial(int(d));
print('Hypo c=',c)
print('sq root d=',d)
print('c*d=',f)
print('c/d=',g)
e=math.log(d)
print('e=',e)
print('h=',h)
print('i= ',i)

Hypo c= 5.385164807134504
sq root d= 2.320595787106084
c*d= 12.496790764308276
c/d= 2.3205957871060834
e= 0.8418239574966185
h= -1.917848549326277
i=  2


In [ ]:
from scipy import *
from numpy import *
import numpy as np

M1=array([[1,2,3],[3,4,5],[1,2,1]])
M2=array([[0,1,2,],[3,4,5],[7,8,2]])
M4=array([[1,2,3,4],[0,3,2,1],[2,1,2,4]])
M3=M1*M2
print('Inverse of M3= \n', np.linalg.inv(M3))
print('Transpose of M3= \n', M3.T)
print('\n M1= \n',M1)
print('\n M2= \n', M2)
print('\n M3= \n',M3)

Inverse of M3= 
 [[-0.72727273  0.18181818 -0.09090909]
 [ 0.31027668 -0.08300395  0.10671937]
 [ 0.06324111  0.02766798 -0.03557312]]
Transpose of M3= 
 [[ 0  9  7]
 [ 2 16 16]
 [ 6 25  2]]

 M1= 
 [[1 2 3]
 [3 4 5]
 [1 2 1]]

 M2= 
 [[0 1 2]
 [3 4 5]
 [7 8 2]]

 M3= 
 [[ 0  2  6]
 [ 9 16 25]
 [ 7 16  2]]
